### PR TITLE
Update protocol document with new findings

### PR DESCRIPTION
**Pull request by normanr**
I recently installed a Clearlight Sauna, which also uses a Gizwits module to provide Wifi connectivity. I'm hoping that I could eventually (after a bunch of updates) use this library to link my sauna with node-red.

As a first pass I've updated the protocol doc with the extra stuff I've been able to discover about the protocol.

Thoughts?

### CODE REVIEW

**Comment by Apollon77** [comment]
WOw, good work, I need to look into it. How far are your plans on finalizing it?

**Comment by normanr** [comment]
I haven't had much time to work on it recently, but the PR as-is is in 100% working state for the existing ph803w device. The functionality and API is unchanged, even though the packet buffer parsing code has been refactored.

My plan was to make a generic `GizwitsDevice` that can have the `dataPoints` definition either set by a sub-class (eg `PH803WDevice`), or auto-discover and download the `dataPoints` from the API server (with an option of caching locally). I haven't had the time to get to that point though (I got distracted by the wireshark dissector and trying to automate generation of the per-product lua scripts from the template script).

Let me know if you'd like me to split up this PR, or if I should just send it for review as-is, so that the changes I've made so far can be merged.

**Comment by Apollon77** [comment]
Hi, we can merge as is if you liek ... I can only test next year because my pool is in winter-break ;-) but testing should rpoof that it still works, so all ok

**Comment by Apollon77** [comment]
Sorry for the very late response, I merged now and release new version soon

**Pull request merged**
